#############################################################################
# Makefile for building: StoplightsApp3.app/Contents/MacOS/StoplightsApp3
# Generated by qmake (2.01a) (Qt 4.8.0) on: Mon Dec 19 22:14:17 2011
# Project:  StoplightsApp3.pro
# Template: app
# Command: /Applications/QtSDK/Desktop/Qt/4.8.0/gcc/bin/qmake -spec /Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/unsupported/macx-clang -o Makefile StoplightsApp3.pro
#############################################################################

####### Compiler, tools and options

CC            = clang
CXX           = clang++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -gdwarf-2 -arch x86_64 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -arch x86_64 -Wall -W $(DEFINES)
INCPATH       = -I/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/unsupported/macx-clang -I. -I/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/lib/QtCore.framework/Versions/4/Headers -I/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/include/QtCore -I/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/lib/QtGui.framework/Versions/4/Headers -I/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/include/QtGui -I/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/include -I. -I. -F/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/lib
LINK          = clang++
LFLAGS        = -headerpad_max_install_names -arch x86_64
LIBS          = $(SUBLIBS) -F/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/lib -L/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/lib -framework QtGui -framework QtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /Applications/QtSDK/Desktop/Qt/4.8.0/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		road.cpp \
		light.cpp moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		road.o \
		light.o \
		moc_mainwindow.o
DIST          = /Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/unix.conf \
		/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/mac.conf \
		/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base.conf \
		/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base-macx.conf \
		/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/clang.conf \
		/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/qconfig.pri \
		/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/modules/qt_webkit_version.pri \
		/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_functions.prf \
		/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_config.prf \
		/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/exclusive_builds.prf \
		/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_pre.prf \
		/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/default_pre.prf \
		/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/dwarf2.prf \
		/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/debug.prf \
		/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_post.prf \
		/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/default_post.prf \
		/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/x86_64.prf \
		/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/objective_c.prf \
		/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/warn_on.prf \
		/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt.prf \
		/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/thread.prf \
		/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/moc.prf \
		/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/rez.prf \
		/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/sdk.prf \
		/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/resources.prf \
		/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/uic.prf \
		/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/yacc.prf \
		/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/lex.prf \
		/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/include_source_dir.prf \
		StoplightsApp3.pro
QMAKE_TARGET  = StoplightsApp3
DESTDIR       = 
TARGET        = StoplightsApp3.app/Contents/MacOS/StoplightsApp3

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-arch \
		x86_64 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile StoplightsApp3.app/Contents/PkgInfo StoplightsApp3.app/Contents/Resources/empty.lproj StoplightsApp3.app/Contents/Info.plist $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) StoplightsApp3.app/Contents/MacOS/ || $(MKDIR) StoplightsApp3.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: StoplightsApp3.pro  /Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/unsupported/macx-clang/qmake.conf /Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/unix.conf \
		/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/mac.conf \
		/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base.conf \
		/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base-macx.conf \
		/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/clang.conf \
		/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/qconfig.pri \
		/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/modules/qt_webkit_version.pri \
		/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_functions.prf \
		/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_config.prf \
		/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/exclusive_builds.prf \
		/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_pre.prf \
		/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/default_pre.prf \
		/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/dwarf2.prf \
		/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/debug.prf \
		/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_post.prf \
		/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/default_post.prf \
		/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/x86_64.prf \
		/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/objective_c.prf \
		/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/warn_on.prf \
		/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt.prf \
		/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/thread.prf \
		/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/moc.prf \
		/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/rez.prf \
		/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/sdk.prf \
		/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/resources.prf \
		/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/uic.prf \
		/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/yacc.prf \
		/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/lex.prf \
		/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec /Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/unsupported/macx-clang -o Makefile StoplightsApp3.pro
/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/unix.conf:
/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/mac.conf:
/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base.conf:
/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base-macx.conf:
/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/clang.conf:
/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/qconfig.pri:
/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/modules/qt_webkit_version.pri:
/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_functions.prf:
/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_config.prf:
/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/exclusive_builds.prf:
/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_pre.prf:
/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/default_pre.prf:
/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/dwarf2.prf:
/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/debug.prf:
/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_post.prf:
/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/default_post.prf:
/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/x86_64.prf:
/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/objective_c.prf:
/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/warn_on.prf:
/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt.prf:
/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/thread.prf:
/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/moc.prf:
/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/rez.prf:
/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/sdk.prf:
/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/resources.prf:
/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/uic.prf:
/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/yacc.prf:
/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/lex.prf:
/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -spec /Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/unsupported/macx-clang -o Makefile StoplightsApp3.pro

StoplightsApp3.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) StoplightsApp3.app/Contents || $(MKDIR) StoplightsApp3.app/Contents 
	@$(DEL_FILE) StoplightsApp3.app/Contents/PkgInfo
	@echo "APPL????" >StoplightsApp3.app/Contents/PkgInfo
StoplightsApp3.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) StoplightsApp3.app/Contents/Resources || $(MKDIR) StoplightsApp3.app/Contents/Resources 
	@touch StoplightsApp3.app/Contents/Resources/empty.lproj
	
StoplightsApp3.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) StoplightsApp3.app/Contents || $(MKDIR) StoplightsApp3.app/Contents 
	@$(DEL_FILE) StoplightsApp3.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,StoplightsApp3,g" -e "s,@TYPEINFO@,????,g" /Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/unsupported/macx-clang/Info.plist.app >StoplightsApp3.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/StoplightsApp31.0.0 || $(MKDIR) .tmp/StoplightsApp31.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/StoplightsApp31.0.0/ && $(COPY_FILE) --parents mainwindow.h ui_mainwindow.h path.h environment.h algorithm.h road.h light.h .tmp/StoplightsApp31.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp road.cpp light.cpp .tmp/StoplightsApp31.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/StoplightsApp31.0.0/ && (cd `dirname .tmp/StoplightsApp31.0.0` && $(TAR) StoplightsApp31.0.0.tar StoplightsApp31.0.0 && $(COMPRESS) StoplightsApp31.0.0.tar) && $(MOVE) `dirname .tmp/StoplightsApp31.0.0`/StoplightsApp31.0.0.tar.gz . && $(DEL_FILE) -r .tmp/StoplightsApp31.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r StoplightsApp3.app
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: mainwindow.h
	/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ mainwindow.h -o moc_mainwindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		road.h \
		ui_mainwindow.h \
		environment.h \
		path.h \
		algorithm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		ui_mainwindow.h \
		road.h \
		environment.h \
		algorithm.h \
		path.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

road.o: road.cpp road.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o road.o road.cpp

light.o: light.cpp light.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o light.o light.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

